/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package gui;

import bean.Activity;
import bean.UsrAct;
import service.ActService;
import service.UsrActService;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author Aealen
 */
public class AdminAddActUI extends javax.swing.JFrame {
    private ActService actService;
    private UsrActService usrActService;
    private Activity activity;
    /** Creates new form AdminUI */
    public AdminAddActUI() {
        actService=new ActService();
        usrActService=new UsrActService();
        activity=new Activity();

        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("学生活动管理系统丨新增活动");
        this.setSize(600,450);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        ActNameText = new javax.swing.JTextField();
        ActNameLabel = new javax.swing.JLabel();
        ActTimeText = new javax.swing.JTextField();
        ActTimeLabel = new javax.swing.JLabel();
        ActDescLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ActDescTextArea = new javax.swing.JTextArea();
        SubmitAddActBt = new javax.swing.JButton();
        AdminActTableScroll = new javax.swing.JScrollPane();
        ActShowTable = new javax.swing.JTable();
        AdminMenu = new javax.swing.JMenuBar();
        ActMenu = new javax.swing.JMenu();
        UsrQueryAct = new javax.swing.JMenuItem();
        UsrEditAct = new javax.swing.JMenuItem();
        UsrMenu = new javax.swing.JMenu();
        UsrQuitSystem = new javax.swing.JMenuItem();
        ActManagementMenu = new javax.swing.JMenu();
        AddAct = new javax.swing.JMenuItem();
        editAct = new javax.swing.JMenuItem();
        UsrManagementMenu = new javax.swing.JMenu();
        UsrManagement = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(600, 400));
        setResizable(false);
        setSize(getSize());

        ActShowTable.setFont(new java.awt.Font("宋体", 0, 13)); // NOI18N
        DefaultTableModel model=new javax.swing.table.DefaultTableModel(
                new Object [][] {

                },
                new String [] {
                        "ID", "Name", "Desc", "Time", "Remain", "Status"
                }
        ) {
            Class[] types = new Class [] {
                    java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                    false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        };
        ActShowTable.setModel(model);
        ActShowTable.setModel(model);
        AdminActTableScroll.setViewportView(ActShowTable);
        if (ActShowTable.getColumnModel().getColumnCount() > 0) {
            ActShowTable.getColumnModel().getColumn(0).setPreferredWidth(40);
            ActShowTable.getColumnModel().getColumn(1).setPreferredWidth(100);
            ActShowTable.getColumnModel().getColumn(2).setPreferredWidth(220);
            ActShowTable.getColumnModel().getColumn(3).setPreferredWidth(80);
            ActShowTable.getColumnModel().getColumn(4).setPreferredWidth(60);
            ActShowTable.getColumnModel().getColumn(5).setPreferredWidth(70);
        }
        ActShowTable.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);//不自动画框

        {
            List<Activity> actList = actService.queryAct();
            int remainNum;
            String Status = new String();
            model.setRowCount(0);
            for (int i = 0; i < actList.size(); i++) {
                remainNum = Integer.valueOf(actList.get(i).getMaxNum()) - Integer.valueOf(actList.get(i).getCurrentNum());
                if (actList.get(i).getStatus().equals("0"))
                    Status = "未进行";
                else if (actList.get(i).getStatus().equals("1"))
                    Status = "正在进行";
                else if (actList.get(i).getStatus().equals("2"))
                    Status = "已结束";
                model.addRow(new Object[]{
                        actList.get(i).getId(),
                        actList.get(i).getName(),
                        actList.get(i).getDesc(),
                        actList.get(i).getTime(),
                        remainNum,
                        Status,
                        usrActService.UsrJoinedAct(actList.get(i))
                });
            }
        }
        ActMenu.setText("活动");


        ActNameText.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N

        ActNameLabel.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N
        ActNameLabel.setText("活动名称：");

        ActTimeText.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        ActTimeText.setText("样式：1999-12-30");
        ActTimeText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ActTimeTextActionPerformed(evt);
            }
        });

        ActTimeLabel.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N
        ActTimeLabel.setText("活动时间：");

        ActDescLabel.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N
        ActDescLabel.setText("活动描述：");

        ActDescTextArea.setColumns(20);
        ActDescTextArea.setRows(5);
        jScrollPane1.setViewportView(ActDescTextArea);

        SubmitAddActBt.setFont(new java.awt.Font("宋体", 0, 13)); // NOI18N
        SubmitAddActBt.setText("提交");
        SubmitAddActBt.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                activity.setName(ActNameText.getText());
                activity.setDesc(ActDescTextArea.getText());
                activity.setTime(ActTimeText.getText());
                if (actService.addAct(activity)){
                    JOptionPane.showMessageDialog(null,"活动添加成功!!!");
                    List<Activity> actList =new ArrayList<Activity>();
                    String Status = new String();
                    actList=actService.queryAct();
                    int remainNum;
                    model.setRowCount(0);
                    for (int i = 0; i <actList.size() ; i++) {
                        remainNum=Integer.valueOf(actList.get(i).getMaxNum())-Integer.valueOf(actList.get(i).getCurrentNum());
                        if (actList.get(i).getStatus().equals("0"))
                            Status="未进行";
                        else if (actList.get(i).getStatus().equals("1"))
                            Status="正在进行";
                        else if (actList.get(i).getStatus().equals("2"))
                            Status="已结束";
                        model.addRow(new Object[]{
                                actList.get(i).getId(),
                                actList.get(i).getName(),
                                actList.get(i).getDesc(),
                                actList.get(i).getTime(),
                                remainNum,
                                Status,
                                usrActService.UsrJoinedAct(actList.get(i))
                        });
                    }

                }
            }
        });



        UsrQueryAct.setText("活动查询");
        UsrQueryAct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsrQueryActActionPerformed(evt);
            }
        });
        ActMenu.add(UsrQueryAct);

        UsrEditAct.setText("活动编辑");
        UsrEditAct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsrEditActActionPerformed(evt);
            }
        });
        ActMenu.add(UsrEditAct);

        AdminMenu.add(ActMenu);

        UsrMenu.setText("用户");

        UsrQuitSystem.setText("注销");
        UsrQuitSystem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsrQuitSystemActionPerformed(evt);
            }
        });
        UsrMenu.add(UsrQuitSystem);

        AdminMenu.add(UsrMenu);

        ActManagementMenu.setText("活动管理");

        AddAct.setText("新增活动");
        AddAct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddActActionPerformed(evt);
            }
        });
        ActManagementMenu.add(AddAct);

        editAct.setText("编辑活动");
        editAct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editActActionPerformed(evt);
            }
        });
        ActManagementMenu.add(editAct);

        AdminMenu.add(ActManagementMenu);

        UsrManagementMenu.setText("用户管理");

        UsrManagement.setText("用户管理");
        UsrManagement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsrManagementActionPerformed(evt);
            }
        });
        UsrManagementMenu.add(UsrManagement);

        AdminMenu.add(UsrManagementMenu);

        setJMenuBar(AdminMenu);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .addContainerGap()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(layout.createSequentialGroup()
                                .add(ActDescLabel)
                                .add(0, 0, 0)
                                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 470, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                            .add(SubmitAddActBt, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 100, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                    .add(layout.createSequentialGroup()
                        .add(18, 18, 18)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(layout.createSequentialGroup()
                                .add(90, 90, 90)
                                .add(ActNameText, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 140, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                            .add(ActNameLabel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 100, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .add(90, 90, 90)
                        .add(ActTimeLabel)
                        .add(0, 0, 0)
                        .add(ActTimeText, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 150, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(layout.createSequentialGroup()
                        .addContainerGap()
                        .add(AdminActTableScroll, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 580, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(ActNameText, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 30, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(ActNameLabel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 30, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(ActTimeLabel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 30, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(ActTimeText, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 30, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(39, 39, 39)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(20, 20, 20)
                        .add(ActDescLabel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 30, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 70, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18)
                .add(SubmitAddActBt)
                .add(26, 26, 26)
                .add(AdminActTableScroll, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 136, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ActTimeTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ActTimeTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ActTimeTextActionPerformed

    private void UsrQueryActActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsrQueryActActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new QueryActUI().setVisible(true);
    }//GEN-LAST:event_UsrQueryActActionPerformed

    private void UsrEditActActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsrEditActActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new EditActUI().setVisible(true);
    }//GEN-LAST:event_UsrEditActActionPerformed

    private void UsrQuitSystemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsrQuitSystemActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new LoginUI().setVisible(true);
    }//GEN-LAST:event_UsrQuitSystemActionPerformed

    private void AddActActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddActActionPerformed
        // TODO add your handling code here:
        //this.dispose();
        //new AdminAddActUI().setVisible(true);
    }//GEN-LAST:event_AddActActionPerformed

    private void editActActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editActActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new AdminEditActUI().setVisible(true);
    }//GEN-LAST:event_editActActionPerformed

    private void UsrManagementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsrManagementActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new UsrManageUI().setVisible(true);
    }//GEN-LAST:event_UsrManagementActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminAddActUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminAddActUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminAddActUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminAddActUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminAddActUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ActDescLabel;
    private javax.swing.JTextArea ActDescTextArea;
    private javax.swing.JMenu ActManagementMenu;
    private javax.swing.JMenu ActMenu;
    private javax.swing.JLabel ActNameLabel;
    private javax.swing.JTextField ActNameText;
    private javax.swing.JTable ActShowTable;
    private javax.swing.JLabel ActTimeLabel;
    private javax.swing.JTextField ActTimeText;
    private javax.swing.JMenuItem AddAct;
    private javax.swing.JScrollPane AdminActTableScroll;
    private javax.swing.JMenuBar AdminMenu;
    private javax.swing.JButton SubmitAddActBt;
    private javax.swing.JMenuItem UsrEditAct;
    private javax.swing.JMenuItem UsrManagement;
    private javax.swing.JMenu UsrManagementMenu;
    private javax.swing.JMenu UsrMenu;
    private javax.swing.JMenuItem UsrQueryAct;
    private javax.swing.JMenuItem UsrQuitSystem;
    private javax.swing.JMenuItem editAct;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables

}
