/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package gui;

import bean.Activity;
import service.ActService;
import service.UsrActService;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.List;

/**
 *
 * @author Aealen
 */
public class EditActUI extends javax.swing.JFrame {
    private ActService actService;
    private UsrActService usrActService;
    private Activity activity;
    /** Creates new form QuitActUI */
    public EditActUI() {
        actService=new ActService();
        usrActService=new UsrActService();
        activity=new Activity();
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("学生活动管理系统丨活动编辑");
        this.setSize(600,450);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AdminActTableScroll = new javax.swing.JScrollPane();
        ActShowTable = new javax.swing.JTable();
        ActIDLabel = new javax.swing.JLabel();
        ActIDText = new javax.swing.JTextField();
        JoinActBt = new javax.swing.JButton();
        QuitActBt = new javax.swing.JButton();
        AdminMenu = new javax.swing.JMenuBar();
        ActMenu = new javax.swing.JMenu();
        UsrQueryAct = new javax.swing.JMenuItem();
        UsrEditAct = new javax.swing.JMenuItem();
        UsrMenu = new javax.swing.JMenu();
        UsrQuitSystem = new javax.swing.JMenuItem();
        ActManagementMenu = new javax.swing.JMenu();
        AddAct = new javax.swing.JMenuItem();
        editAct = new javax.swing.JMenuItem();
        UsrManagementMenu = new javax.swing.JMenu();
        UsrManagement = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ActShowTable.setFont(new java.awt.Font("宋体", 0, 13)); // NOI18N
        DefaultTableModel model=new javax.swing.table.DefaultTableModel(
                new Object [][] {

                },
                new String [] {
                        "ID", "Name", "Desc", "Time", "Remain", "Status", "Joined"
                }
        ) {
            Class[] types = new Class [] {
                    java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                    false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        };
        ActShowTable.setModel(model);
        AdminActTableScroll.setViewportView(ActShowTable);
        if (ActShowTable.getColumnModel().getColumnCount() > 0) {
            ActShowTable.getColumnModel().getColumn(0).setPreferredWidth(30);
            ActShowTable.getColumnModel().getColumn(1).setPreferredWidth(80);
            ActShowTable.getColumnModel().getColumn(2).setPreferredWidth(200);
            ActShowTable.getColumnModel().getColumn(3).setPreferredWidth(80);
            ActShowTable.getColumnModel().getColumn(4).setPreferredWidth(60);
            ActShowTable.getColumnModel().getColumn(5).setPreferredWidth(70);
            ActShowTable.getColumnModel().getColumn(6).setPreferredWidth(50);
        }
        ActShowTable.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);//不自动画框

        /**
         * 打开这个页面是 先输出全部活动信息
         */
        {
            List<Activity> actList = actService.queryAct();
            int remainNum;
            String Status = new String();
            model.setRowCount(0);
            for (int i = 0; i < actList.size(); i++) {
                remainNum = Integer.valueOf(actList.get(i).getMaxNum()) - Integer.valueOf(actList.get(i).getCurrentNum());
                if (actList.get(i).getStatus().equals("0"))
                    Status = "未进行";
                else if (actList.get(i).getStatus().equals("1"))
                    Status = "正在进行";
                else if (actList.get(i).getStatus().equals("2"))
                    Status = "已结束";
                model.addRow(new Object[]{
                        actList.get(i).getId(),
                        actList.get(i).getName(),
                        actList.get(i).getDesc(),
                        actList.get(i).getTime(),
                        remainNum,
                        Status,
                        usrActService.UsrJoinedAct(actList.get(i))
                });
            }
        }

        ActIDLabel.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N
        ActIDLabel.setText("活动ID：");

        ActIDText.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N
        ActIDText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ActIDTextActionPerformed(evt);
            }
        });

        JoinActBt.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N
        JoinActBt.setText("参加活动");
        JoinActBt.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                if (ActIDText.getText().length()!=0)
                activity=actService.queryActById(ActIDText.getText()).get(0);

                activity=actService.queryActById(String.valueOf(ActShowTable.getValueAt(ActShowTable.getSelectedRow(),0))).get(0);

                if(usrActService.UsrJoinAct(activity)){
                    JOptionPane.showMessageDialog(null,"成功参加活动!!");
                    usrActService.usrJoinWithNumAdd(activity);
                    List<Activity> actList = actService.queryAct();
                    int remainNum;
                    String Status = new String();
                    model.setRowCount(0);
                    for (int i = 0; i < actList.size(); i++) {
                        remainNum = Integer.valueOf(actList.get(i).getMaxNum()) - Integer.valueOf(actList.get(i).getCurrentNum());
                        if (actList.get(i).getStatus().equals("0"))
                            Status = "未进行";
                        else if (actList.get(i).getStatus().equals("1"))
                            Status = "正在进行";
                        else if (actList.get(i).getStatus().equals("2"))
                            Status = "已结束";
                        model.addRow(new Object[]{
                                actList.get(i).getId(),
                                actList.get(i).getName(),
                                actList.get(i).getDesc(),
                                actList.get(i).getTime(),
                                remainNum,
                                Status,
                                usrActService.UsrJoinedAct(actList.get(i))
                        });
                    }
                }
            }
        });

        QuitActBt.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N
        QuitActBt.setText("退出活动");
        QuitActBt.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {

                if (ActIDText.getText().length()!=0)
                    activity=actService.queryActById(ActIDText.getText()).get(0);
                activity=actService.queryActById(String.valueOf(ActShowTable.getValueAt(ActShowTable.getSelectedRow(),0))).get(0);
                if (usrActService.UsrQuitAct(activity)){
                    JOptionPane.showMessageDialog(null,"退出活动成功!!");
                    usrActService.usrQuitWithNumMin(activity);
                    List<Activity> actList = actService.queryAct();
                    int remainNum;
                    String Status = new String();
                    model.setRowCount(0);
                    for (int i = 0; i < actList.size(); i++) {
                        remainNum = Integer.valueOf(actList.get(i).getMaxNum()) - Integer.valueOf(actList.get(i).getCurrentNum());
                        if (actList.get(i).getStatus().equals("0"))
                            Status = "未进行";
                        else if (actList.get(i).getStatus().equals("1"))
                            Status = "正在进行";
                        else if (actList.get(i).getStatus().equals("2"))
                            Status = "已结束";
                        model.addRow(new Object[]{
                                actList.get(i).getId(),
                                actList.get(i).getName(),
                                actList.get(i).getDesc(),
                                actList.get(i).getTime(),
                                remainNum,
                                Status,
                                usrActService.UsrJoinedAct(actList.get(i))
                        });
                    }
                }else {
                    JOptionPane.showMessageDialog(null,"你并没有参加这个活动!!");
                }
            }
        });

        ActMenu.setText("活动");

        UsrQueryAct.setText("活动查询");
        UsrQueryAct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsrQueryActActionPerformed(evt);
            }
        });
        ActMenu.add(UsrQueryAct);

        UsrEditAct.setText("活动编辑");
        UsrEditAct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsrEditActActionPerformed(evt);
            }
        });
        ActMenu.add(UsrEditAct);

        AdminMenu.add(ActMenu);

        UsrMenu.setText("用户");

        UsrQuitSystem.setText("注销");
        UsrQuitSystem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsrQuitSystemActionPerformed(evt);
            }
        });
        UsrMenu.add(UsrQuitSystem);

        AdminMenu.add(UsrMenu);

        ActManagementMenu.setText("活动管理");

        AddAct.setText("新增活动");
        AddAct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddActActionPerformed(evt);
            }
        });
        ActManagementMenu.add(AddAct);

        editAct.setText("编辑活动");
        editAct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editActActionPerformed(evt);
            }
        });
        ActManagementMenu.add(editAct);

        AdminMenu.add(ActManagementMenu);

        UsrManagementMenu.setText("用户管理");

        UsrManagement.setText("用户管理");
        UsrManagement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsrManagementActionPerformed(evt);
            }
        });
        UsrManagementMenu.add(UsrManagement);

        AdminMenu.add(UsrManagementMenu);

        setJMenuBar(AdminMenu);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(22, 22, 22)
                .add(ActIDLabel)
                .add(18, 18, 18)
                .add(ActIDText, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 127, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(34, 34, 34)
                .add(JoinActBt)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(QuitActBt)
                .add(52, 52, 52))
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(AdminActTableScroll, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 580, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(AdminActTableScroll, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE)
                .add(63, 63, 63)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                        .add(ActIDLabel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(ActIDText, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 37, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                        .add(JoinActBt)
                        .add(QuitActBt)))
                .add(48, 48, 48))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void UsrQueryActActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsrQueryActActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new QueryActUI().setVisible(true);
    }//GEN-LAST:event_UsrQueryActActionPerformed

    private void UsrEditActActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsrEditActActionPerformed
        // TODO add your handling code here:
        //this.dispose();
        //new EditActUI().setVisible(true);
    }//GEN-LAST:event_UsrEditActActionPerformed

    private void UsrQuitSystemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsrQuitSystemActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new LoginUI().setVisible(true);
    }//GEN-LAST:event_UsrQuitSystemActionPerformed

    private void AddActActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddActActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new AdminAddActUI().setVisible(true);
    }//GEN-LAST:event_AddActActionPerformed

    private void editActActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editActActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new AdminEditActUI().setVisible(true);
    }//GEN-LAST:event_editActActionPerformed

    private void ActIDTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ActIDTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ActIDTextActionPerformed

    private void UsrManagementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsrManagementActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new UsrManageUI().setVisible(true);
    }//GEN-LAST:event_UsrManagementActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
         } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditActUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditActUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditActUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditActUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditActUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ActIDLabel;
    private javax.swing.JTextField ActIDText;
    private javax.swing.JMenu ActManagementMenu;
    private javax.swing.JMenu ActMenu;
    private javax.swing.JTable ActShowTable;
    private javax.swing.JMenuItem AddAct;
    private javax.swing.JScrollPane AdminActTableScroll;
    private javax.swing.JMenuBar AdminMenu;
    private javax.swing.JButton JoinActBt;
    private javax.swing.JButton QuitActBt;
    private javax.swing.JMenuItem UsrEditAct;
    private javax.swing.JMenuItem UsrManagement;
    private javax.swing.JMenu UsrManagementMenu;
    private javax.swing.JMenu UsrMenu;
    private javax.swing.JMenuItem UsrQueryAct;
    private javax.swing.JMenuItem UsrQuitSystem;
    private javax.swing.JMenuItem editAct;
    // End of variables declaration//GEN-END:variables

}
