/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import bean.User;
import service.UsrService;

import javax.swing.*;
import java.io.*;

/**
 *
 * @author Aealen
 */
public class LoginUI extends javax.swing.JFrame {

    private UsrService usrService;
    private User user;


    /**
     * Creates new form LoginUI
     */
    public LoginUI() {
        usrService=new UsrService();
        user=new User();
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("学生活动管理系统丨登录");
        this.setSize(600,450);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        id = new javax.swing.JLabel();
        pwd = new javax.swing.JLabel();
        idInput = new javax.swing.JTextField();
        regBt = new javax.swing.JButton();
        loginBt = new javax.swing.JButton();
        pwdInput = new javax.swing.JPasswordField();
        loginLabel = new javax.swing.JLabel();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        id.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N
        id.setText("账号:");

        pwd.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N
        pwd.setText("密码:");

        idInput.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N
        idInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idInputActionPerformed(evt);
            }
        });

        regBt.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N
        regBt.setText("注册");
        regBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regBtActionPerformed(evt);
            }
        });

        loginBt.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N
        loginBt.setText("登录");
        loginBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginBtActionPerformed(evt);
            }
        });

        pwdInput.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N
        pwdInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pwdInputActionPerformed(evt);
            }
        });

        loginLabel.setFont(new java.awt.Font("宋体", 0, 36)); // NOI18N
        loginLabel.setText("登     录");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(regBt)
                .addGap(109, 109, 109)
                .addComponent(loginBt)
                .addGap(166, 166, 166))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 143, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pwd, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(idInput, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pwdInput, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(96, 96, 96))
            .addGroup(layout.createSequentialGroup()
                .addGap(209, 209, 209)
                .addComponent(loginLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(loginLabel)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idInput))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pwd, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pwdInput, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(97, 97, 97)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(regBt)
                    .addComponent(loginBt))
                .addGap(34, 34, 34))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void idInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idInputActionPerformed

    private void pwdInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pwdInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pwdInputActionPerformed

    private void regBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regBtActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new RegUI().setVisible(true);
    }//GEN-LAST:event_regBtActionPerformed

    /**
     * 登录
     * @param evt
     */
    private void loginBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBtActionPerformed
        // TODO add your handling code here:
        if (usrService.UsrLogin(idInput.getText(),pwdInput.getText())){
            user.setName(idInput.getText());
            usrService.UpdateLogInTime(user);
            usrService.UsrAuthorFileWrite(user.getName());
            if (usrService.UsrIsAdmin(idInput.getText())) {
                //管理员登录成功
                this.dispose();
                new QueryActUI().setVisible(true);
            }
            else{
                //普通用户登录成功
                this.dispose();
                usrService.UpdateLogInTime(user);
                new UsrActQueryUI().setVisible(true);
            }
        }else {
            //登陆失败   原因1.未注册   2.用户名或密码错误
            JOptionPane.showMessageDialog(null,"用户名或密码错误,请重试!!");
            pwdInput.requestFocus();
            pwdInput.setSelectionStart(0);
            pwdInput.setSelectionEnd(pwdInput.getText().length());
        }

    }//GEN-LAST:event_loginBtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel id;
    private javax.swing.JTextField idInput;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JButton loginBt;
    private javax.swing.JLabel loginLabel;
    private javax.swing.JLabel pwd;
    private javax.swing.JPasswordField pwdInput;
    private javax.swing.JButton regBt;
    // End of variables declaration//GEN-END:variables
}
